---
- name: stop rabbitmq app
  shell: rabbitmqctl stop_app

- name: reset rabbitmq app
  shell: rabbitmqctl reset

- name: join rabbitmq cluster
  shell: "rabbitmqctl join_cluster rabbit@{{ rabbitmq_cluster_master }}"
  register: rabbitmq_cluster
  ignore_errors: True

- name: ensure rabbitmq cluster member
  fail: msg="Unable to join the cluster."
  when: ("'already_member' not in rabbitmq_output.stderr") and rabbitmq_output.rc != 0

- name: start rabbitmq app
  shell: rabbitmqctl start_app
